name: README build
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
        continue-on-error: true

      - name: Get Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        continue-on-error: true

      - name: Configure pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/cache/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
        continue-on-error: true

      - name: Install dependencies
        run: python -m pip install -r cache/requirements.txt
        continue-on-error: true

      - name: Update README file
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: |
          echo "Running today.py script..."
          time python today.py
        continue-on-error: true

      - name: Commit changes
        run: |
          git config --global user.email "github-actions-bot@github.com"
          git config --global user.name "GitHub Actions Bot"
          git add .
          git commit -m "Updated README" -a || echo "No changes to commit"
        continue-on-error: true

      - name: Push changes
        run: |
          echo "Pushing changes..."
          time git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        continue-on-error: true
