name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set Environment Variables
      run: echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> $GITHUB_ENV
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    - name: Set Environment Variables USER_NAME
      run: echo "USER_NAME=${{ secrets.USER_NAME }}" >> $GITHUB_ENV
      env:
        USER_NAME: ${{ secrets.USER_NAME }}

    - name: Run Python Script
      run: |
        set -o pipefail
        python today.py 2>&1 | tee script.log
        if [ ${PIPESTATUS[0]} -ne 0 ]; then
          echo "Script failed. Check script.log for details."
          exit 1
        fi

    - name: Upload Log
      uses: actions/upload-artifact@v3
      with:
        name: script-log
        path: script.log

    - name: Notify on Failure
      if: failure()
      run: |
        echo "The workflow has failed. Check the logs for details."
        echo "Script log:"
        cat script.log
